### ISSUE TITLE
File naming convention integration

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#40]
One of the PGE's core responsibilities is assignment of file names to output products/metadata created by the SAS or PGE. This ticket tracks integration of initial functionality for the PGE to derive a filename according to project conventions, as well as rename applicable output files using the filename.

For release 1 (DSWx-HLS PGE), we will start by adopting the filename convention defined by ADT in the DSWx-HLS Product Spec:

    <Project>_<Level>_<ProductType>_<Source>_<Sensor>_<TileID>_<DateTime>_<ProductVersion>.<ext>

    Project: "OPERA"
    Level: "L3"
    ProductType: "DSWx"
    Source: "HLS"
    Sensor: "Sentinel2A", "Sentinel2B"  or "Landsat8"
    TileID: Specific tile id of the product which is also the tile id of the input HLS product in the military grid system
    DateTime: The acquisition date and time of the input satellite imagery for this product in YYYYMMDDTHHMMSS format
    ProductVersion: Version of HLS product used to generated the DSWx ouput product

    Example:
    OPERA_L3_DSWx_HLS_Sentinel2_T15SXR_20210201T163901_1.0.tiff

The base_pge.py module should define the core functionality for generation and application of file name conventions, and inheritors (such as the DSWx-HLS) should be responsible for defining the specific field values to be utilized in the naming conventions (for example, defining "DSWx" as the product type, "HLS" as the source etc...).

Some fields, such as `TileID`, `DateTime` and `ProductVersion` will need to be parsed from an HLS input file processed by the PGE. The `Sensor` field will need to be obtained from the output GeoTiff file generated by the SAS. Parsing of these fields should occur in the Post-processor mixin for the DSWx PGE.

**Comment by hfattahi** [comment]
@collinss-jpl just a heads up that the product spec will be slightly updated regarding the output product in the next release. Specifically in the delivered version we had one GTiff file with multiple bands. Unfortunately this is not possible anymore since we have few bands with different data types (GTiff requires all bands have the same data type). Similar to input HLS we are going with multiple output files for the DSWX-HLS (one file per band). The naming convention will be similar except that we will update it to indicate the specific layers.

**Comment by collinss-jpl** [comment]
@hfattahi Understood, thanks for the heads up!
