### ISSUE TITLE
Add issue templates to PGE repo

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#45]
opera-sds-pge repository is still in need of issue templates for pull requests, bug reports, feature requests etc...

@riverma has kindly provided some samples here as a starting point

Feature requests:
https://raw.githubusercontent.com/aria-jpl/coseismic_enumerator/main/.github/ISSUE_TEMPLATE/feature_request.md

Bug reports:
https://raw.githubusercontent.com/aria-jpl/coseismic_enumerator/main/.github/ISSUE_TEMPLATE/bug_report.md

Issues:
https://aria-jpl.github.io/#/?id=issues

Note links may require JPL vpn to access.

**Comment by riverma** [comment]
@collinss-jpl - thanks for setting this up.

My vote for templates is to start out with the aforementioned Feature Request and Bug Report templates and to set up [issue forms for them](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). One benefit is the templates are based on GitHub standard issue templates, so many devs will feel familiar with filing them. The "Issue" template is probably unnecessary at this point since it overlaps with the earlier two. 

@collinss-jpl @hhlee445 what do you think about starting with those templates? If you're happy with them, I'm happy to post a quick PR to set it up for this repo and /opera-sds-pcm

**Comment by collinss-jpl** [comment]
@riverma Templates look fine to me, was going to try and knock this ticket out this week but if you'd like to submit a PR I won't stand in your way

**Comment by hhlee445** [comment]
@riverma Templates look good. I agree with Scott.
